### ISSUE TITLE
Hydrogent: axes are rendered to depth on MacOS

### ISSUE THREAD

**Issue by TheMostDiligent** [DiligentGraphics/DiligentFX#147]
It may be a bug since depth writes are disabled.

**Comment by MikhailGorobets** [comment]
@TheMostDiligent 
The problem is not with the depth but with the normal map, we should not overwrite it when rendering axes.
<img width="670" alt="image" src="https://github.com/DiligentGraphics/DiligentFX/assets/25492259/16ec1a53-6e88-4dba-bcb2-df88aeea0d3a">

**Comment by MikhailGorobets** [comment]
I think when rendering axes we only need to render in Scene Color and Motion Vectors RTVs. Also, we probably need two separate buffers for the velocity map (one with axes and one without), one to pass in SSAO and SSR steps, the other in TAA

**Comment by TheMostDiligent** [comment]
Axes were removed in 311b20112ba04e5a9cd643e4bccaeadc5e2aa566 and replaced with coordinate grid in #154
