### ISSUE TITLE
SSR: Latest changes broke reflections on OpenGL

### ISSUE THREAD

**Issue by MikhailGorobets** [DiligentGraphics/DiligentFX#151]
This commit broke reflections on OpenGL
https://github.com/DiligentGraphics/DiligentFX/commit/64deda8d453f7db4eb7db23c31759cbf960ac9fa

**Comment by TheMostDiligent** [comment]
How is it broken? Everything seems to be working OK, including WebGL

**Comment by MikhailGorobets** [comment]
@TheMostDiligent Try to check PostFX demo
