### ISSUE TITLE
Bloom flickering from bright spikes

### ISSUE THREAD

**Issue by TheMostDiligent** [DiligentGraphics/DiligentFX#182]
TAA causes temporal flickering which is blurred by bloom.

One solution that can  help is to use median filter before applying blur - this will remove bright outliers

**Comment by MikhailGorobets** [comment]
Fixed in https://github.com/DiligentGraphics/DiligentFX/commit/4fea7fbfc8b7330b768452cf7a60d1063dcb4e29
