### ISSUE TITLE
CMake doesn't see new shader files

### ISSUE THREAD

**Issue by MikhailGorobets** [DiligentGraphics/DiligentFX#196]
When creating a new shader file, we need to regenerate project solution

**Comment by TheMostDiligent** [comment]
Yes, this is how CMake works, there is no other way. It is like when you add a new source file, you also need to regenerate the solution.

We use globbing expression to collect all shaders:

```
file(GLOB_RECURSE SHADERS LIST_DIRECTORIES false Shaders/*.*)
```

Whenever you add a new shader, the list needs to be updated, but there is no way for CMake to detect that a file was added or removed. CMake only tracks CMakeLists.txt files
