### ISSUE TITLE
Improve performance of IBL cubemap precomputation

### ISSUE THREAD

**Issue by TheMostDiligent** [DiligentGraphics/DiligentFX#204]
IBL precomputation currently takes too much time on some low-end devices causes driver to crash.
The shader needs to be optimized.
One thing that should help is to precompute Hammersley2D sequence and store it in a constant buffer (use float4 for each element of the sequence).

**Comment by MikhailGorobets** [comment]
Computing Irradiance Cube Map 640x640 per side with 8192 samples on GPU - AMD Radeon(TM) 610M:
* Hammersley Current Version:
D3D12 - 7814.65 ms Vulkan -  13118.9 ms
* Hammersley Imrpoved:
D3D12- 6423.19 ms Vulkan - 11336.2 ms
* Golden Ratio
D3D12 - 6855.13 ms Vulkan - 11735.5 ms
