### ISSUE TITLE
Use the SHADER_VARIABLE_FLAG_NO_DYNAMIC_BUFFERS flag for constant buffers in post-effects

### ISSUE THREAD

**Issue by MikhailGorobets** [DiligentGraphics/DiligentFX#215]

**Comment by TheMostDiligent** [comment]
@MikhailGorobets this is not necessary.
This flag improves performance a bit in D3D12 and Vulkan. It only makes a measurable difference when draw command is called 1000+ times.
For post-processing effects this will not make a differences.

**Comment by TheMostDiligent** [comment]
This is a very minor optimization, not worth spending time on it.
