### ISSUE TITLE
Make USD Viewer run on WebGPU

### ISSUE THREAD

**Issue by TheMostDiligent** [DiligentGraphics/DiligentFX#224]
Since PBR renderer and post-processing already work, there should not be many issues.
Required https://github.com/DiligentGraphics/DiligentFX/issues/227

**Comment by TheMostDiligent** [comment]
@MikhailGorobets 76b946e00a7caad2b3ac548e6133cd00e9cd1bed fixes GLTFViewer on WebGPU.
Please check if it works in the browser and fix any remaining issues.

**Comment by TheMostDiligent** [comment]
@MikhailGorobets Please fix the remaining debug group errors.

**Comment by MikhailGorobets** [comment]
Moved to https://github.com/DiligentGraphics/DiligentCore/pull/577
