### ISSUE TITLE
SSR: reflection take much longer time to appear in D3D11 and D3D12

### ISSUE THREAD

**Issue by TheMostDiligent** [DiligentGraphics/DiligentFX#226]
Compare how Tutorial 27 works in D3D11/D3D12 and GL/VK modes

**Comment by MikhailGorobets** [comment]
This is not a bug. Shaders in D3D are compiled without locks, so the first frame appears earlier. In glslang, there is a bug in multi-threaded compilation that blocks the main thread, so the first frame appears later in Vulkan (during this time, the value responsible for interpolation changes)
